# This is a basic workflow to help you get started with Actions

name: first-workflow
on: workflow_dispatch

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello GitHub Action"
      - name: second-step
        run: |
          echo "we're enjoying GitHub Action"
          echo "Bye, done"
    
